language: node_js
node_js:
  - "6"
before_install:
  - npm i -g npm@5
script: npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: docs
  local_dir: ./dist/
