language: node_js
node_js:
  - "node"
  - "lts/*"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
services:
  - xvfb
addons:
  firefox: "latest"
cache: yarn
